name: Deploy PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      - name: Copy
        run: |
          mkdir out
          cp ./resume.pdf ./out/resume.pdf
          cp ./index.html ./out/index.html
      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: |
            out/resume.pdf 
            out/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          single-commit: true
          folder: out
          git-config-name: timlechmanbot
          git-config-email: bot@noreply.timlechman.com